#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    VI_VSB = SAFE_RANGE,
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch(keycode) {
        case VI_VSB:
        if (record->event.pressed) {
            SEND_STRING("$V%");
        }
        return false;
    }
    return true;
}

const uint16_t PROGMEM copy_combo[] = {KC_C, KC_V, COMBO_END};
const uint16_t PROGMEM paste_combo[] = {KC_V, KC_B, COMBO_END};
const uint16_t PROGMEM cut_combo[] = {KC_X, KC_C, COMBO_END};
const uint16_t PROGMEM undo_combo[] = {KC_Z, KC_X, COMBO_END};

enum combos {
    COPY_COMBO,
    PASTE_COMBO,
    CUT_COMBO,
    UNDO_COMBO
};

combo_t key_combos[] = {
    [COPY_COMBO] = COMBO(copy_combo, LGUI(KC_C)),
    [PASTE_COMBO] = COMBO(paste_combo, LGUI(KC_V)),
    [CUT_COMBO] = COMBO(cut_combo, LGUI(KC_X)),
    [UNDO_COMBO] = COMBO(undo_combo, LGUI(KC_Z)),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // Main Layer
    [0] = LAYOUT_split_3x6_3(
        KC_ESC,        KC_Q,         KC_W,         KC_E,         KC_R,          KC_T,                       KC_Y,     KC_U,         KC_I,         KC_O,         KC_P,            KC_BSLS,
        KC_MINS,       LCTL_T(KC_A), LALT_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F),  KC_G,                       KC_H,     LSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN), KC_QUOT,
        LSFT(KC_LALT), KC_Z,         KC_X,         KC_C,         KC_V,          KC_B,                       KC_N,     KC_M,         KC_COMM,      KC_DOT,       KC_SLSH,         LCTL(KC_UP),
                                                                 TT(2),         MO(1),   KC_ENT,    KC_SPC, KC_LSFT,  KC_BSPC
    ),
    // Symbols Layer
    [1] = LAYOUT_split_3x6_3(
        TO(0), KC_NO,   KC_AT,   KC_LCBR, KC_RCBR, VI_VSB,                                   LSFT(KC_SCLN),  KC_PLUS, KC_ASTR, KC_EXLM, KC_LGUI, QK_BOOT,
        KC_DEL,      KC_HASH, KC_DLR,  KC_LPRN, KC_RPRN, KC_TAB,                                   KC_MINS,        KC_EQL,  KC_GT,   KC_PIPE, KC_TILD, KC_SLSH,
        KC_CAPS,     KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_GRV,                                   KC_AMPR,        KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, CW_TOGG,
                                                         KC_NO,   KC_NO, KC_TRNS,         KC_TRNS, KC_LGUI,        KC_TRNS
    ),
    // Numpad Layer
    [2] = LAYOUT_split_3x6_3(
        TO(0),      KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_MUTE,                                   KC_HOME, KC_7,    KC_8,    KC_9,    KC_SLSH, KC_ASTR,
        KC_MINS,    KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_VOLU,                                   KC_END,  KC_4,    KC_5,    KC_6,    KC_PLUS, KC_PGUP,
        KC_TRNS,    KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_VOLD,                                   KC_0,    KC_1,    KC_2,    KC_3,    KC_DOT,  KC_PGDN,
                                                        KC_TRNS, KC_TRNS, KC_TRNS,        KC_TRNS, KC_TRNS, KC_NO
    )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
